---
output: pdf_document
params:
  PIN:
    label: "PIN"
    value: "NA"
    input: text
  target:
    label: "DataFrame"
    value: ""  
  comps:
    label: "DataFrame"
    value: ""
title: '`r paste0("Comparables for ", params$PIN)`'
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

options(kableExtra.latex.load_packages = FALSE)

library(knitr)
library(kableExtra)
library(tidyverse)
library(scales)

usepackage_latex("booktabs")
usepackage_latex("longtable")
usepackage_latex("array")
usepackage_latex("multirow")
usepackage_latex("xcolor", "table")
usepackage_latex("wrapfig")
usepackage_latex("float")
usepackage_latex("colortbl")
usepackage_latex("pdflscape")
usepackage_latex("tabu")
usepackage_latex("threeparttable")
usepackage_latex("threeparttablex")
usepackage_latex("ulem", "normalem")
usepackage_latex("makecell")

target <- as.data.frame(params$target)
comps <- as.data.frame(params$comps)

comps <- comps %>% select(PIN:CERTIFIED)

final_names <- c("Pin", "Class", "Age", "Building Sqft", "Land Sqft", "Rooms", "Bedrooms", "Wall Material", "Stories", "Basement", "Garage", "Distance", "2019 Certified Value")


prettify_df <- function(df){
  names(df) <- final_names
  df <- df %>% mutate(
    Distance = paste0(round(as.numeric(Distance), 2), " miles"),
    `2019 Certified Value` = dollar(as.numeric(`2019 Certified Value`))
  )
}

target <- prettify_df(target)
comps <- prettify_df(comps)

```

# Target Property Information

```{r}
kable(target, "latex", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down"))
```

# List of Comparables

```{r}
kable(comps, "latex", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "scale_down"))

hypen_pin <- paste0(str_sub(params$PIN, 1, 2), "-", 
                    str_sub(params$PIN, 3, 4), "-", 
                    str_sub(params$PIN, 5, 7), "-", 
                    str_sub(params$PIN, 8, 10), "-",
                    str_sub(params$PIN, 11, 14))

write_csv(comps, paste0("tmp_data/Comparable PINs for ", hypen_pin, ".csv"))
```

